-- MySQL Script generated by MySQL Workbench
-- dim. 14 mai 2023 11:19:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- -----------------------------------------------------
-- Schema pizzahutte_admin_db
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pizzahutte_admin_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzahutte_admin_db`;
USE `pizzahutte_admin_db`;
-- -----------------------------------------------------
-- Table `pizzahutte_admin_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzahutte_admin_db`.`users` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `email` VARCHAR(70) NULL,
    `password` VARCHAR(70) NULL,
    `nom` VARCHAR(70) NULL,
    `prenom` VARCHAR(70) NULL,
    PRIMARY KEY (`id`)
)